In [2]:
import torch
inputs = torch.tensor([[0.43, 0.15, 0.89], 
[0.57, 0.85, 0.64],
[0.22, 0.58, 0.33],
[0.77, 0.25, 0.10],
[0.05, 0.80, 0.55]]
)

/Users/pranamshetty/Developer/workshop/transformers-from-scratch/venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [3]:
query = inputs[1]
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query)
print(attn_scores_2)

tensor([0.9422, 1.4570, 0.8296, 0.7154, 1.0605])


In [4]:
print(inputs.shape[0])

5


In [5]:
res = 0
for idx, element in enumerate(inputs[0]):
    res += inputs[0][idx] * query[idx]
print(res)
print(torch.dot(inputs[0], query))

tensor(0.9422)
tensor(0.9422)


In [6]:
attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()
print("Attention weights:", attn_weights_2_tmp)
print("Sum:", attn_weights_2_tmp.sum())

Attention weights: tensor([0.1883, 0.2911, 0.1658, 0.1429, 0.2119])
Sum: tensor(1.0000)


In [7]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)
attn_weights_2_naive = softmax_naive(attn_scores_2)
print(attn_weights_2_naive)
print(attn_weights_2_naive.sum())

tensor([0.1822, 0.3048, 0.1628, 0.1452, 0.2050])
tensor(1.)


In [8]:
attn_weights_2 = torch.softmax(attn_scores_2, dim = 0)
print(attn_weights_2)
print(attn_weights_2.sum())


tensor([0.1822, 0.3048, 0.1628, 0.1452, 0.2050])
tensor(1.)


In [9]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * x_i
print(context_vec_2)

tensor([0.4099, 0.5812, 0.5382])


In [10]:
attn_scores = torch.empty(6, 6)
for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = torch.dot(x_i, x_j)
print(attn_scores)

tensor([[0.9995, 0.9422, 0.4753, 0.4576, 0.6310, 0.0000],
        [0.9422, 1.4570, 0.8296, 0.7154, 1.0605, 0.0000],
        [0.4753, 0.8296, 0.4937, 0.3474, 0.6565, 0.0000],
        [0.4576, 0.7154, 0.3474, 0.6654, 0.2935, 0.0000],
        [0.6310, 1.0605, 0.6565, 0.2935, 0.9450, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])


In [11]:
attn_scores = inputs @ inputs.T
print(attn_scores)

tensor([[0.9995, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9422, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0605, 0.6565, 0.2935, 0.9450]])


In [12]:
attn_weights = torch.softmax(attn_scores, dim = -1)

In [13]:
print(attn_weights)

tensor([[0.2625, 0.2479, 0.1554, 0.1527, 0.1816],
        [0.1822, 0.3048, 0.1628, 0.1452, 0.2050],
        [0.1811, 0.2581, 0.1844, 0.1593, 0.2171],
        [0.1898, 0.2456, 0.1700, 0.2336, 0.1611],
        [0.1772, 0.2722, 0.1817, 0.1264, 0.2425]])


In [14]:
row_2_sum = sum(        [0.1822, 0.3048, 0.1628, 0.1452, 0.2050],
)

In [15]:
row_2_sum

1.0

In [16]:
all_context_vecs = attn_weights @ inputs
print(all_context_vecs)

tensor([[0.4150, 0.5236, 0.5587],
        [0.4099, 0.5812, 0.5382],
        [0.3991, 0.5670, 0.5225],
        [0.4469, 0.5230, 0.4941],
        [0.3808, 0.5890, 0.5379]])


In [17]:
print("Previous 2nd context vector:", context_vec_2)

Previous 2nd context vector: tensor([0.4099, 0.5812, 0.5382])


In [ ]:
#attention with weights
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [19]:
torch.manual_seed(123)
W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_key = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad = False)

In [20]:
query_2 = x_2 @ W_query
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)

tensor([0.4300, 1.4343])


In [21]:
keys = inputs @ W_key
values = inputs @ W_value
print(keys.shape)
print(values.shape)

torch.Size([5, 2])
torch.Size([5, 2])


In [24]:
# key_2 = keys[2]
attn_score_22 = query_2.dot(key_2)
print(attn_score_22)

tensor(1.0654)


In [25]:
attn_scores_2 = query_2 @ keys.T
print(attn_scores_2)

tensor([1.2544, 1.7877, 1.0654, 0.5508, 1.5238])


In [27]:
d_k = keys.shape[-1]
print(d_k)

2


In [28]:
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**0.5, dim = -1)
print(attn_weights_2)

tensor([0.1941, 0.2831, 0.1699, 0.1180, 0.2349])


In [29]:
context_vec_2 = attn_weights_2 @ values
print(context_vec_2)

tensor([0.2797, 0.7668])


In [30]:
#self attention class
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))
    
    def forward(self, x):
        keys = x @ self.W_key
        queries = x @ self.W_query
        values = x @ self.W_value
        attn_scores = queries @ keys.T  
        attn_weights = torch.softmax ( attn_scores / keys.shape[-1]**0.5, dim = -1)
        context_vec = attn_weights @ values
        return context_vec
    
    

In [31]:
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.2741, 0.7524],
        [0.2797, 0.7668],
        [0.2698, 0.7416],
        [0.2679, 0.7371],
        [0.2736, 0.7512]], grad_fn=<MmBackward0>)


In [37]:
class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias = False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias = qkv_bias)
        self.W_key = nn.Linear( d_in, d_out, bias = qkv_bias )
        self.W_value = nn.Linear(d_in, d_out, bias = qkv_bias)

    def forward ( self, x): 
        queries = self.W_query(x)
        keys = self.W_key(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores/keys.shape[-1]**0.5, dim = -1)
        context_vec = attn_weights @ values
        return context_vec


In [38]:
torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.0661,  0.0703],
        [-0.0671,  0.0690],
        [-0.0685,  0.0668],
        [-0.0689,  0.0662],
        [-0.0678,  0.0679]], grad_fn=<MmBackward0>)


In [40]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim = -1)
print(attn_weights)

tensor([[0.2300, 0.1977, 0.1855, 0.2060, 0.1807],
        [0.2441, 0.1993, 0.1796, 0.1995, 0.1775],
        [0.2243, 0.2002, 0.1885, 0.1993, 0.1877],
        [0.2197, 0.2004, 0.1907, 0.1990, 0.1902],
        [0.2321, 0.1998, 0.1849, 0.1998, 0.1834]], grad_fn=<SoftmaxBackward0>)


In [41]:
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [42]:
masked_simple = attn_weights * mask_simple
print(masked_simple)

tensor([[0.2300, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2441, 0.1993, 0.0000, 0.0000, 0.0000],
        [0.2243, 0.2002, 0.1885, 0.0000, 0.0000],
        [0.2197, 0.2004, 0.1907, 0.1990, 0.0000],
        [0.2321, 0.1998, 0.1849, 0.1998, 0.1834]], grad_fn=<MulBackward0>)


In [43]:
row_sums = masked_simple.sum(dim = -1, keepdim = True)
masked_simple_norm = masked_simple/ row_sums
print(masked_simple_norm)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5504, 0.4496, 0.0000, 0.0000, 0.0000],
        [0.3659, 0.3266, 0.3075, 0.0000, 0.0000],
        [0.2713, 0.2475, 0.2354, 0.2458, 0.0000],
        [0.2321, 0.1998, 0.1849, 0.1998, 0.1834]], grad_fn=<DivBackward0>)


In [45]:
mask = torch.triu(torch.ones(context_length, context_length), diagonal = 1)
print(mask)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked)

tensor([[0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])
tensor([[0.2899,   -inf,   -inf,   -inf,   -inf],
        [0.4594, 0.1731,   -inf,   -inf,   -inf],
        [0.2642, 0.1036, 0.0186,   -inf,   -inf],
        [0.2183, 0.0882, 0.0177, 0.0786,   -inf],
        [0.3408, 0.1290, 0.0198, 0.1290, 0.0078]],
       grad_fn=<MaskedFillBackward0>)


In [46]:
attn_weights = torch.softmax(masked/ keys.shape[-1]** 0.5, dim = 1 )
print(attn_weights)

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5504, 0.4496, 0.0000, 0.0000, 0.0000],
        [0.3659, 0.3266, 0.3075, 0.0000, 0.0000],
        [0.2713, 0.2475, 0.2354, 0.2458, 0.0000],
        [0.2321, 0.1998, 0.1849, 0.1998, 0.1834]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# DROPOUT
